include CommandLineInvocationTypes

let usageText = CommandLineInvocationShared.usageText

let helpRequestedOfArguments =
  CommandLineInvocationShared.helpRequestedOfArguments

let invocationOfArguments = CommandLineInvocationParser.invocationOfArguments
